//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniLibProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public int Id { get; set; }
        public string name { get; set; }
        public Nullable<decimal> code { get; set; }
        public string author { get; set; }
        public string Genere { get; set; }
        public Nullable<System.DateTime> BorrowDate { get; set; }
        public Nullable<int> MemberId { get; set; }
    }
}
