//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniLibProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int Id { get; set; }
        public string email { get; set; }
        public Nullable<decimal> Phone { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public Nullable<System.DateTime> date_charged { get; set; }
        public Nullable<int> days_left { get; set; }
        public Nullable<decimal> charge { get; set; }
        public string name { get; set; }
        public string pass { get; set; }
        public byte[] pic { get; set; }
    }
}
